import LocalizedStrings from 'react-native-localization';
import { PASSWORD_MIN_LENGTH } from './constant';

const LocalizedString = new LocalizedStrings({
    'en-US': {
        common: {
            alertTitleInfo: 'INFO',
            alertTitleError: 'ERROR',
            alertTitleWarning: 'WARNING',
            alertTitleConfirmation: 'CONFIRMATION',

            buttonCaptionOK: 'OK',
            buttonCaptionCancel: 'CANCEL',
            buttonCaptionDetail: 'DETAIL',
            buttonCaptionYes: 'YES',
            buttonCaptionNo: 'NO',
            buttonCaptionSave: 'SAVE',
            buttonCaptionEdit: 'EDIT',
            buttonCaptionSubmit: 'SUBMIT',
            buttonCaptionNext: 'NEXT',
            buttonCaptionPrev: 'PREV',
            buttonCaptionBack: 'BACK',
            buttonCaptionUpdate: 'UPDATE',
            buttonCaptionApprove: 'Approve',
            buttonCaptionReject: 'Reject',
            buttonCaptionSelectFile: 'Select File',
            buttonCaptionClose: 'Close',
            buttonCaptionTakePicture: 'Take Picture',
            buttonCaptionTakeVideo: 'Take Video',

            placeholderEmail: 'your-email@domain.com',
            placeholderAppSearch: 'Search Application Name',

            errMsgEmptyRequiredFields: 'Required fields cannot be empty',
            errMsgInvalidEmailFormat: 'The email address is invalid',
            errMsgInvalidPhoneNumberFormat: 'The phone number format is invalid',
            errMsgMinPasswordLength: `Minimum password length is ${PASSWORD_MIN_LENGTH} characters`,
            errMsgPasswordDoesNotMatch: 'The password does not match',
            errMsgCannotOpenUrl: 'Cannot open the URL',
            errMsgNoResultFound: 'No Data Available',
            errMsgRequired: 'Required',
            errMsgLocationPermission: 'Location permission isn\'t granted',
            errMsgInvalidQRCode: 'Invalid QR Code',
            errMsgInvalidNotification: 'This notification is invalid',
            errMsgPermissionNotGranted: 'Permission to Read File not Granted',
            errMsgEmptySelectOption: 'Select option cannot be empty',

            msgTaskApprovalApproveConfirmation: 'Are you sure want to approve this task?',
            msgTaskApprovalRejectConfirmation: 'Are you sure want to reject this task?',

            footerIconLabelHome: 'Home',
            footerIconLabelTasklist: 'Tasklist',
            footerIconLabelProfile: 'Profile',

            labelRequiredField: 'This Field Is Required',
            labelChooseAction: 'Choose Action',
        },
        loginScreen: {
            title: 'Log In',
            description: 'Sign in to start consulting',
            buttonCaptionLogin: 'Sign In',
            buttonCaptionForgetPassword: 'Forget Password ?',
            buttonCaptionRegister: 'Register',
            labelUsername: 'Username',
            labelEmail: 'Email',
            labelPassword: 'Password',
            labelRegister: 'Don\'t have an account yet?',
            errEmptyUsernamePassword: 'Email and password cannot be empty',
        },
        registerEmailScreen: {
            title: 'Registration',
            description: 'Write your email here. We will send a PIN to your email to continue the registration process',
            labelFullName: 'Full Name',
            labelJobTitle: 'Job Title',
            labelEmail: 'Email',
            labelPassword: 'Password',
            labelConfirmPassword: 'Confirm Password',
            buttonCaptionRegister: 'Continue',
        },
        getStartedScreen: {
            description: 'Consultation with a doctor becomes easier & more flexible',
            buttonCaptionRegister: 'Get Started',
            buttonCaptionLogin: 'Sign In',
        },
        uploadPhotoScreen: {
            title: 'Upload Photo',
            buttonCaptionContinue: 'Upload and Continue',
            buttonCaptionSkip: 'Skip for this',
        },
        resetPasswordScreen: {
            title: 'Reset Password',
            description: 'Type your new password',
            labelPassword: 'password',
            labelConfirmPassword: 'retype your password',
        },
        profileScreen: {
            title: 'Profile',
            msgLogoutConfirmation: 'Are you sure you want to logout?',

        },

    },
    in: {
        common: {
            alertTitleInfo: 'INFO',
            alertTitleError: 'GALAT',
            alertTitleWarning: 'PERINGATAN',
            alertTitleConfirmation: 'KONFIRMASI',

            buttonCaptionOK: 'OK',
            buttonCaptionCancel: 'BATAL',
            buttonCaptionDetail: 'DETAIL',
            buttonCaptionYes: 'YA',
            buttonCaptionNo: 'TIDAK',
            buttonCaptionSave: 'SIMPAN',
            buttonCaptionEdit: 'UBAH',
            buttonCaptionSubmit: 'KIRIM',
            buttonCaptionNext: 'LANJUT',
            buttonCaptionPrev: 'SEBELUMNNYA',
            buttonCaptionBack: 'KEMBALI',
            buttonCaptionUpdate: 'PERBARUI',
            buttonCaptionApprove: 'Setuju',
            buttonCaptionReject: 'Tolak',
            buttonCaptionSelectFile: 'Pilih File',
            buttonCaptionClose: 'Tutup',
            buttonCaptionTakePicture: 'Ambil Foto',
            buttonCaptionTakeVideo: 'Ambil Video',

            placeholderEmail: 'email-anda@domain.com',
            placeholderAppSearch: 'Cari Nama Aplikasi',

            errMsgEmptyRequiredFields: 'Tidak boleh ada field yang kosong',
            errMsgInvalidEmailFormat: 'Format email yang Anda masukkan salah',
            errMsgInvalidPhoneNumberFormat: 'Format nomor telepon yang Anda masukkan salah',
            errMsgMinPasswordLength: `Minimal panjang password adalah ${PASSWORD_MIN_LENGTH} karakter`,
            errMsgPasswordDoesNotMatch: 'Kedua kata sandi tidak cocok',
            errMsgCannotOpenUrl: 'Tidak bisa membuka URL',
            errMsgNoResultFound: 'Tidak ada Data Ditemukan',
            errMsgRequired: 'Harus diisi',
            errMsgLocationPermission: 'Akses lokasi tidak diizinkan',
            errMsgInvalidQRCode: 'Kode QR tidak dikenal',
            errMsgInvalidNotification: 'Notif sudah tidak valid',
            errMsgPermissionNotGranted: 'Izin Membaca File Tidak Diberikan',
            errMsgEmptySelectOption: 'Pilihan tidak boleh kosong',
            msgTaskApprovalApproveConfirmation: 'Apa Anda yakin ingin menyetujui tugas ini?',
            msgTaskApprovalRejectConfirmation: 'Apa Anda yakin ingin menolak tugas ini?',

            footerIconLabelHome: 'Beranda',
            footerIconLabelTasklist: 'Daftar Tugas',
            footerIconLabelProfile: 'Profil',

            labelRequiredField: 'Field Ini Harus Diisi',
            labelChooseAction: 'Pilih Tindakan',
        },
        loginScreen: {
            title: 'Masuk',
            description: 'Masuk untuk memulai konsultasi',
            buttonCaptionLogin: 'Masuk',
            buttonCaptionForgetPassword: 'Lupa Sandi ?',
            buttonCaptionRegister: 'Daftar',
            labelUsername: 'Nama Pengguna',
            labelEmail: 'Email',
            labelPassword: 'Kata Sandi',
            labelRegister: 'Belum punya akun?',
            errEmptyUsernamePassword: 'Email dan Sandi tidak boleh kosong',
        },
        registerEmailScreen: {
            title: 'Pendaftaran',
            description: 'Tulis email Anda di sini. Kami akan mengirim PIN ke email Anda yang bisa digunakan untuk melanjutkan proses registrasi',
            labelFullName: 'Nama Lengkap',
            labelJobTitle: 'Pekerjaan',
            labelEmail: 'Email',
            labelPassword: 'Password',
            labelConfirmPassword: 'Ulangi Password',
            buttonCaptionRegister: 'Lanjutkan',
        },
        getStartedScreen: {
            description: 'Konsultasi dengan dokter jadi lebih mudah & fleksibel',
            buttonCaptionRegister: 'Memulai',
            buttonCaptionLogin: 'Masuk',
        },
        uploadPhotoScreen: {
            title: 'Unggah Foto',
            buttonCaptionContinue: 'Unggah dan Lanjut',
            buttonCaptionSkip: 'Lewati',
        },
        resetPasswordScreen: {
            title: 'Buat Password',
            description: 'Tulis password baru Anda',
            labelPassword: 'password',
            labelConfirmPassword: 'tulis ulang password',
        },
        profileScreen: {
            title: 'Profil',
            msgLogoutConfirmation: 'Anda yakin ingin keluar?',
        },

    },
});

export default LocalizedString;
